app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Kiwunaka
publisher_url: https://github.com/NikitaSH999/PORTALapp
display_name: PORTAL VPN
executable_name: PORTALVPN.exe
output_base_file_name: PORTALVPN-setup
create_desktop_icon: true
install_dir_name: "{autopf64}\\PORTAL VPN"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - fa
  - ru
  - pt
  - tr
script_template: inno_setup.sas
