name: Upload store MSIX to release

permissions:
  contents: write

on:
  release:
    types: [released]

  workflow_dispatch:

jobs:
  upload-store-msix-to-release:
    if: ${{ github.event_name != 'release' || startsWith(github.event.release.tag_name, 'v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Upload store MSIX to release
        uses: hiddify/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release@develop
        with:
          store-id: 9pdfnl3qv2s5
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name-pattern: pokrov-windows-setup-x64
